<?php

namespace Database\Seeders;

use App\Models\Sport;
use App\Models\Team;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GroupSeeder extends Seeder
{
    private array $nameMap = [
        'Бөөрөлжүүт цахилгаан станц'     => 'Бөөрөлжүүтийн цахилгаан станц',
        'Бөөрөлжүүт Цахилгаан Станц'     => 'Бөөрөлжүүтийн цахилгаан станц',
        'Бөөрөлжүүт дулааны станц'       => 'Бөөрөлжүүтийн цахилгаан станц',
        'ДҮТ ТӨХХК'                       => 'Диспетчерийн үндэсний төв',
        'ӨБЦТС ТӨХК'                      => 'Өмнөд бүсийн цахилгаан түгээх сүлжээ ТӨХК',
        'Даланзадгадын ДЦС ТӨХК'         => 'Даланзадгадын Дулааны Цахилгаан станц ТӨХК',
        'Даланзадгад ДЦС ТӨХК'           => 'Даланзадгадын Дулааны Цахилгаан станц ТӨХК',
        'Даланзадгадын дулааны станц'    => 'Даланзадгадын Дулааны Цахилгаан станц ТӨХК',
        'Даланзадгад дулааны станц'      => 'Даланзадгадын Дулааны Цахилгаан станц ТӨХК',
        'ДЦС-2 ТӨХК'                      => 'Дулааны цахилгаан станц-2 ТӨХК',
        'ДЦС-3 ТӨХК'                      => 'Дулааны цахилгаан станц-3 ТӨХК',
        'ДЦС-3'                           => 'Дулааны цахилгаан станц-3 ТӨХК',
        'ДЦС-4 ТӨХК'                      => 'Дулааны цахилгаан станц-4 ТӨХК',
        'ДЦС-4'                           => 'Дулааны цахилгаан станц-4 ТӨХК',
        'ББЦТС ТӨХК'                      => 'Баруун бүсийн цахилгаан түгээх сүлжээ ТӨХК',
        'ХАСУ Даян ХХК'                  => 'Хасу мегаватт',
        'Хасу Даян ХХК'                  => 'Хасу мегаватт',
        'ХАСУ даян ХХК'                  => 'Хасу мегаватт',
        'Хасу даян ХХК'                  => 'Хасу мегаватт',
        'УБДС ТӨХК'                       => 'Улаанбаатар дулааны сүлжээ ТӨХК',
        'Эрчим хүчний яам'               => 'Эрчим хүчний яам Эрчим хүчний зохицуулах хороо',
        'Эрчим Хүчний яам'               => 'Эрчим хүчний яам Эрчим хүчний зохицуулах хороо',
        'ЭХЗХ'                            => 'Эрчим хүчний яам Эрчим хүчний зохицуулах хороо',
        'ЭХЗХ '                           => 'Эрчим хүчний яам Эрчим хүчний зохицуулах хороо',
        'ЦДҮС ТӨХК'                       => 'Цахилгаан дамжуулах үндэсний сүлжээ ТӨХК',
        'УБЦТС ТӨХК'                      => 'Улаанбаатар цахилгаан түгээх сүлжээ ТӨХК',
        'ЭХҮТ ТӨХХК'                      => 'Эрчим хүчний үндэсний төв ТӨХХК',
        'Монхорус ХХК'                    => 'Монхорус эрчим ХХК',
        'ДДЦС ТӨХК'                       => 'Дархан дулааны цахилгаан станц ТӨХК',
        'ДДЦСтанц ТӨХК'                  => 'Дархан дулааны цахилгаан станц ТӨХК',
        'БНЗӨБЦТС ТӨХК'                  => 'Багануур зүүн-өмнөд бүсийн цахилгаан түгээх сүлжээ ТӨХК',
        'БНЗӨБЦС ТӨХК'                   => 'Багануур зүүн-өмнөд бүсийн цахилгаан түгээх сүлжээ ТӨХК',
        'ЭДЦС ТӨХК'                       => 'Эрдэнэтийн дулааны цахилгаан станц ТӨХК',
        'Говь НЦС'                        => 'Говь НЦС',
        'Хөвсгөл Дулааны станц ТӨХК'     => 'Хөвсгөл Дулааны Станц ТӨХК',
        'Хөвсгөлийн дулааны станц'       => 'Хөвсгөл Дулааны Станц ТӨХК',
        'АУЦТС ТӨХК'                      => 'Алтай-Улиастайн цахилгаан түгээх сүлжээ ТӨХК',
        'ЭБЦТС ТӨХК'                      => 'Эрдэнэт булганы цахилгаан түгээх сүлжээ ТӨХК',
        'ДДСүлжээ ТӨХК'                  => 'Дархан дулааны сүлжээ ТӨХК',
        'ДДС ТӨХК'                        => 'Дархан дулааны сүлжээ ТӨХК',
        'Налайх дулааны станц'           => 'Налайх Дулааны Станц',
        'Налайх Дулааны станц'           => 'Налайх Дулааны Станц',
        'Багануур дулааны станц'         => 'Багануур Дулааны Станц',
        'Багануур дулааны станц ТӨХК'    => 'Багануур Дулааны Станц',
        'Багануур Дулааны станц'         => 'Багануур Дулааны Станц',
        'Амгалан дулааны станц'          => 'Амгалан Дулааны Станц',
        'ДСЦТС ТӨХК'                      => 'Дархан сэлэнгийн цахилгаан түгээх сүлжээ ХК',
        'ДСЦТС ХХК'                       => 'Дархан сэлэнгийн цахилгаан түгээх сүлжээ ХК',
        'ДСЦТС'                           => 'Дархан сэлэнгийн цахилгаан түгээх сүлжээ ХК',
        'Тайшир-Ногоон эрчим хүч'        => 'Тайшир-ногоон эрчим хүч',
        'Тайшир ногоон эрчим хүч'        => 'Тайшир-ногоон эрчим хүч',
        'Тайшир ногоон эрчим '           => 'Тайшир-ногоон эрчим хүч',
        'Баян-Өлгий ЦТС ТӨХК'           => 'Баян-Өлгий ЦТС',
        'УДЦС ТӨХК'                       => 'Улаанбаатар Дулааны Цахилгаан Станц ТӨХК',
    ];

    // [slug, gender, group, order, xlsx_name]
    private function getData(): array
    {
        return [
            // САГС эрэгтэй
            ['basketball','male','A',1,'Бөөрөлжүүт цахилгаан станц'],
            ['basketball','male','A',2,'ДҮТ ТӨХХК'],
            ['basketball','male','A',3,'ӨБЦТС ТӨХК'],
            ['basketball','male','A',4,'Даланзадгадын ДЦС ТӨХК'],
            ['basketball','male','B',1,'ДЦС-2 ТӨХК'],
            ['basketball','male','B',2,'Тайшир-ногоон эрчим хүч'],
            ['basketball','male','B',3,'Амгалан дулааны станц'],
            ['basketball','male','B',4,'ББЦТС ТӨХК'],
            ['basketball','male','C',1,'ХАСУ Даян ХХК'],
            ['basketball','male','C',2,'УБДС ТӨХК'],
            ['basketball','male','C',3,'Эрчим хүчний яам'],
            ['basketball','male','C',4,'ЦДҮС ТӨХК'],
            ['basketball','male','D',1,'УБЦТС ТӨХК'],
            ['basketball','male','D',2,'ЭХҮТ ТӨХХК'],
            ['basketball','male','D',3,'ЭХЗХ'],
            ['basketball','male','E',1,'ЭБЦТС ТӨХК'],
            ['basketball','male','E',2,'Монхорус ХХК'],
            ['basketball','male','E',3,'ДДЦС ТӨХК'],
            ['basketball','male','F',1,'БНЗӨБЦТС ТӨХК'],
            ['basketball','male','F',2,'Ньюком ХХК'],
            ['basketball','male','F',3,'Баян-Өлгий ЦТС'],
            ['basketball','male','G',1,'ЭДЦС ТӨХК'],
            ['basketball','male','G',2,'Говь НЦС'],
            ['basketball','male','G',3,'ДЦС-4 ТӨХК'],
            ['basketball','male','H',1,'Багануур дулааны станц'],
            ['basketball','male','H',2,'ДЦС-3 ТӨХК'],
            ['basketball','male','H',3,'Хөвсгөл Дулааны станц ТӨХК'],
            ['basketball','male','H',4,'АУЦТС ТӨХК'],
            // САГС эмэгтэй
            ['basketball','female','A',1,'Даланзадгад ДЦС ТӨХК'],
            ['basketball','female','A',2,'ДҮТ ТӨХХК'],
            ['basketball','female','A',3,'ЭХЗХ'],
            ['basketball','female','B',1,'Тайшир-Ногоон эрчим хүч'],
            ['basketball','female','B',2,'ДЦС-2 ТӨХК'],
            ['basketball','female','B',3,'Ньюком ХХК'],
            ['basketball','female','C',1,'Бөөрөлжүүт Цахилгаан Станц'],
            ['basketball','female','C',2,'ББЦТС ТӨХК'],
            ['basketball','female','C',3,'ЭХҮТ ТӨХХК'],
            ['basketball','female','D',1,'УБДС ТӨХК'],
            ['basketball','female','D',2,'Монхорус ХХК'],
            ['basketball','female','D',3,'УДЦС ТӨХК'],
            ['basketball','female','E',1,'АУЦТС ТӨХК'],
            ['basketball','female','E',2,'ДЦС-4 ТӨХК'],
            ['basketball','female','E',3,'ХАСУ даян ХХК'],
            ['basketball','female','F',1,'Амгалан дулааны станц'],
            ['basketball','female','F',2,'ДЦС-2 ТӨХК'],
            ['basketball','female','F',3,'Эрчим хүчний яам'],
            ['basketball','female','G',1,'УБЦТС ТӨХК'],
            ['basketball','female','G',2,'БНЗӨБЦТС ТӨХК'],
            ['basketball','female','G',3,'ДДЦС ТӨХК'],
            ['basketball','female','H',1,'Багануур дулааны станц'],
            ['basketball','female','H',2,'ӨБЦТС ТӨХК'],
            ['basketball','female','H',3,'ЦДҮС ТӨХК'],
            // ВОЛЕЙБОЛ эрэгтэй
            ['volleyball','male','A',1,'ДЦС-4'],
            ['volleyball','male','A',2,'ӨБЦТС ТӨХК'],
            ['volleyball','male','A',3,'УБЦТС ТӨХК'],
            ['volleyball','male','A',4,'ДДС ТӨХК'],
            ['volleyball','male','B',1,'Багануур дулааны станц ТӨХК'],
            ['volleyball','male','B',2,'Даланзадгад ДЦС ТӨХК'],
            ['volleyball','male','B',3,'ДДЦС ТӨХК'],
            ['volleyball','male','B',4,'ДЦС-2 ТӨХК'],
            ['volleyball','male','C',1,'Хөвсгөл Дулааны станц ТӨХК'],
            ['volleyball','male','C',2,'АУЦТС ТӨХК'],
            ['volleyball','male','C',3,'ЦДҮС ТӨХК'],
            ['volleyball','male','C',4,'Ньюком ХХК'],
            ['volleyball','male','D',1,'ДҮТ ТӨХХК'],
            ['volleyball','male','D',2,'Налайх дулааны станц'],
            ['volleyball','male','D',3,'ДЦС-3'],
            ['volleyball','male','D',4,'УБДС ТӨХК'],
            ['volleyball','male','E',1,'Хасу Даян ХХК'],
            ['volleyball','male','E',2,'Эрчим хүчний яам'],
            ['volleyball','male','E',3,'Амгалан дулааны станц'],
            ['volleyball','male','E',4,'ЭХЗХ'],
            ['volleyball','male','F',1,'ДСЦТС ТӨХК'],
            ['volleyball','male','F',2,'Тайшир ногоон эрчим хүч'],
            ['volleyball','male','F',3,'Баян-Өлгий ЦТС'],
            ['volleyball','male','G',1,'БНЗӨБЦТС ТӨХК'],
            ['volleyball','male','G',2,'ЭДЦС ТӨХК'],
            ['volleyball','male','G',3,'ЭХҮТ ТӨХХК'],
            ['volleyball','male','H',1,'ББЦТС ТӨХК'],
            ['volleyball','male','H',2,'Бөөрөлжүүт цахилгаан станц'],
            ['volleyball','male','H',3,'Монхорус ХХК'],
            // ВОЛЕЙБОЛ эмэгтэй
            ['volleyball','female','A',1,'АУЦТС ТӨХК'],
            ['volleyball','female','A',2,'ДЦС-2 ТӨХК'],
            ['volleyball','female','A',3,'Бөөрөлжүүт дулааны станц'],
            ['volleyball','female','A',4,'ХАСУ Даян ХХК'],
            ['volleyball','female','B',1,'ДҮТ ТӨХХК'],
            ['volleyball','female','B',2,'УБЦТС ТӨХК'],
            ['volleyball','female','B',3,'Багануур дулааны станц'],
            ['volleyball','female','B',4,'Эрчим хүчний яам'],
            ['volleyball','female','C',1,'УДЦС ТӨХК'],
            ['volleyball','female','C',2,'Налайх дулааны станц'],
            ['volleyball','female','C',3,'ДЦС-4 ТӨХК'],
            ['volleyball','female','D',1,'ЭХЗХ'],
            ['volleyball','female','D',2,'ДДСүлжээ ТӨХК'],
            ['volleyball','female','D',3,'ДЦС-3 ТӨХК'],
            ['volleyball','female','E',1,'ББЦТС ТӨХК'],
            ['volleyball','female','E',2,'Монхорус ХХК'],
            ['volleyball','female','E',3,'БНЗӨБЦТС ТӨХК'],
            ['volleyball','female','F',1,'Ньюком ХХК'],
            ['volleyball','female','F',2,'ӨБЦТС ТӨХК'],
            ['volleyball','female','F',3,'Амгалан дулааны станц'],
            ['volleyball','female','G',1,'ЦДҮС ТӨХК'],
            ['volleyball','female','G',2,'ДДЦСтанц ТӨХК'],
            ['volleyball','female','G',3,'Тайшир ногоон эрчим хүч'],
            ['volleyball','female','H',1,'Даланзадгад дулааны станц'],
            ['volleyball','female','H',2,'ЭБЦТС ТӨХК'],
            ['volleyball','female','H',3,'Хөвсгөлийн дулааны станц'],
            // ТЕННИС эрэгтэй
            ['table-tennis','male','A',1,'Налайх дулааны станц'],
            ['table-tennis','male','A',2,'УБЦТС ТӨХК'],
            ['table-tennis','male','A',3,'Даланзадгадын дулааны станц'],
            ['table-tennis','male','A',4,'Эрчим хүчний яам'],
            ['table-tennis','male','B',1,'БНЗӨБЦС ТӨХК'],
            ['table-tennis','male','B',2,'Бөөрөлжүүт цахилгаан станц'],
            ['table-tennis','male','B',3,'ББЦТС ТӨХК'],
            ['table-tennis','male','B',4,'АУЦТС ТӨХК'],
            ['table-tennis','male','C',1,'ХАСУ даян ХХК'],
            ['table-tennis','male','C',2,'ДЦС-3'],
            ['table-tennis','male','C',3,'Баян-Өлгий ЦТС ТӨХК'],
            ['table-tennis','male','C',4,'Багануур дулааны станц'],
            ['table-tennis','male','D',1,'ЭХЗХ'],
            ['table-tennis','male','D',2,'ЭДЦС ТӨХК'],
            ['table-tennis','male','D',3,'ЦДҮС ТӨХК'],
            ['table-tennis','male','E',1,'ДЦС-4 ТӨХК'],
            ['table-tennis','male','E',2,'ДДЦС ТӨХК'],
            ['table-tennis','male','E',3,'ӨБЦТС ТӨХК'],
            ['table-tennis','male','F',1,'ЭХҮТ ТӨХХК'],
            ['table-tennis','male','F',2,'Ньюком ХХК'],
            ['table-tennis','male','F',3,'ДЦС-2 ТӨХК'],
            ['table-tennis','male','G',1,'Амгалан дулааны станц'],
            ['table-tennis','male','G',2,'Тайшир ногоон эрчим хүч'],
            ['table-tennis','male','G',3,'ДСЦТС'],
            ['table-tennis','male','H',1,'ДҮТ ТӨХХК'],
            ['table-tennis','male','H',2,'Монхорус ХХК'],
            ['table-tennis','male','H',3,'УБДС ТӨХК'],
            // ТЕННИС эмэгтэй
            ['table-tennis','female','A',1,'ББЦТС ТӨХК'],
            ['table-tennis','female','A',2,'ЦДҮС ТӨХК'],
            ['table-tennis','female','A',3,'ЭХҮТ ТӨХХК'],
            ['table-tennis','female','A',4,'Амгалан дулааны станц'],
            ['table-tennis','female','B',1,'ДҮТ ТӨХХК'],
            ['table-tennis','female','B',2,'ЭДЦС ТӨХК'],
            ['table-tennis','female','B',3,'ДСЦТС ХХК'],
            ['table-tennis','female','B',4,'ДДЦС ТӨХК'],
            ['table-tennis','female','C',1,'Ньюком ХХК'],
            ['table-tennis','female','C',2,'ДЦС-3 ТӨХК'],
            ['table-tennis','female','C',3,'АУЦТС ТӨХК'],
            ['table-tennis','female','C',4,'Бөөрөлжүүт дулааны станц'],
            ['table-tennis','female','D',1,'Хасу Даян ХХК'],
            ['table-tennis','female','D',2,'ӨБЦТС ТӨХК'],
            ['table-tennis','female','D',3,'Монхорус ХХК'],
            ['table-tennis','female','D',4,'Эрчим хүчний яам'],
            ['table-tennis','female','E',1,'ДЦС-4 ТӨХК'],
            ['table-tennis','female','E',2,'БНЗӨБЦТС ТӨХК'],
            ['table-tennis','female','E',3,'УБЦТС ТӨХК'],
            ['table-tennis','female','E',4,'Тайшир ногоон эрчим хүч'],
            ['table-tennis','female','F',1,'Налайх дулааны станц'],
            ['table-tennis','female','F',2,'Даланзадгад дулааны станц'],
            ['table-tennis','female','F',3,'ЭХЗХ'],
            ['table-tennis','female','F',4,'УБДС ТӨХК'],
            // ОЛС ТАТАЛТ
            ['tug-of-war','mixed','A',1,'ДҮТ ТӨХХК'],
            ['tug-of-war','mixed','A',2,'Монхорус ХХК'],
            ['tug-of-war','mixed','A',3,'ЦДҮС ТӨХК'],
            ['tug-of-war','mixed','A',4,'ДДЦС ТӨХК'],
            ['tug-of-war','mixed','A',5,'ББЦТС ТӨХК'],
            ['tug-of-war','mixed','A',6,'ДЦС-3 ТӨХК'],
            ['tug-of-war','mixed','B',1,'Амгалан дулааны станц'],
            ['tug-of-war','mixed','B',2,'ДЦС-2 ТӨХК'],
            ['tug-of-war','mixed','B',3,'Ньюком ХХК'],
            ['tug-of-war','mixed','B',4,'УБЦТС ТӨХК'],
            ['tug-of-war','mixed','B',5,'ДСЦТС'],
            ['tug-of-war','mixed','B',6,'Тайшир ногоон эрчим хүч'],
            ['tug-of-war','mixed','C',1,'ДЦС-4 ТӨХК'],
            ['tug-of-war','mixed','C',2,'ЭХҮТ ТӨХХК'],
            ['tug-of-war','mixed','C',3,'АУЦТС ТӨХК'],
            ['tug-of-war','mixed','C',4,'Хасу даян ХХК'],
            ['tug-of-war','mixed','C',5,'ЭДЦС ТӨХК'],
            ['tug-of-war','mixed','C',6,'БНЗӨБЦТС ТӨХК'],
            ['tug-of-war','mixed','C',7,'Эрчим хүчний яам'],
            ['tug-of-war','mixed','D',1,'ӨБЦТС ТӨХК'],
            ['tug-of-war','mixed','D',2,'Багануур дулааны станц'],
            ['tug-of-war','mixed','D',3,'Бөөрөлжүүт дулааны станц'],
            ['tug-of-war','mixed','D',4,'Даланзадгадын дулааны станц'],
            ['tug-of-war','mixed','D',5,'УБДС ТӨХК'],
            ['tug-of-war','mixed','D',6,'ДДСүлжээ ТӨХК'],
        ];
    }

    public function run(): void
    {
        DB::table('group_assignments')->truncate();

        $teamCache  = Team::pluck('id', 'name')->toArray();
        $sportCache = Sport::pluck('id', 'slug')->toArray();

        $inserted = 0;
        $missing  = [];

        foreach ($this->getData() as [$slug, $gender, $group, $order, $xlsxName]) {
            $dbName  = $this->nameMap[$xlsxName] ?? $xlsxName;
            $teamId  = $teamCache[$dbName] ?? null;
            $sportId = $sportCache[$slug]  ?? null;

            if (!$teamId) { $missing[] = $xlsxName; continue; }
            if (!$sportId) continue;

            DB::table('group_assignments')->insertOrIgnore([
                'sport_id'   => $sportId,
                'gender'     => $gender,
                'group_name' => $group,
                'team_id'    => $teamId,
                'order_num'  => $order,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $inserted++;
        }

        if ($missing) {
            $this->command->warn('Олдоогүй багууд: ' . implode(', ', array_unique($missing)));
        }
        $this->command->info("Бүртгэгдлээ: {$inserted} мөр");
    }
}
